### ISSUE TITLE
Clubhouse API V2

### ISSUE THREAD

**Issue by camilleacey** [PhilipCastiglione/clubhouse_ruby#1]
I just wanted to let you know that we've released [Clubhouse V2](https://clubhouse.io/api/rest/v2/). While V1 will continue to be supported, V2 exposes endpoints for several new features such as Teams, Milestones, and Categories.

**Comment by PhilipCastiglione** [comment]
Great, thanks for the heads up! I'll look into whats required to update clubhouse_ruby.

**Comment by PhilipCastiglione** [comment]
I've updated the gem for V2 of the API.

**Comment by camilleacey** [comment]
Great. Thanks so much!
