### ISSUE TITLE
New gem release?

### ISSUE THREAD

**Issue by palcalde** [PhilipCastiglione/clubhouse_ruby#4]
Hey Philip, I'm forced to use git master branch in my Gemfile to get the updates you merged on this PR https://github.com/PhilipCastiglione/clubhouse_ruby/pull/3

Could you release a new version to rubygems?

Thank you!

**Comment by PhilipCastiglione** [comment]
Apologies, I'll release the new version

**Comment by PhilipCastiglione** [comment]
I've released 0.5.0 including the search stories changes. Sorry it took me so long! Let me know if you have any problems 😄
