### ISSUE TITLE
Clubhouse V3 API

### ISSUE THREAD

**Issue by svanzoest** [PhilipCastiglione/clubhouse_ruby#5]
It looks like Clubhouse has released a V3 version of the API https://clubhouse.io/api/rest/v3/
Unfortunately, it is not very clear as to what is different.

**Comment by PhilipCastiglione** [comment]
Thanks for the heads up, I'll take a look.

**Comment by svanzoest** [comment]
This is the related blog post https://clubhouse.io/blog/api-v3
> In most circumstances, this will simply be changing v1, v2, or beta to v3 in the URL string. In certain circumstances, you may need to rework your logic or even use a different endpoint.

**Comment by PhilipCastiglione** [comment]
I've updated the gem, it took a while because of IRL things. Hope it wasn't an inconvenience.

I've refreshed some tests and all the vcr cassettes and it looks like everything still works. Let me know if you have any difficulties!
